---
recording:
  output_dir: recordings
  channels: 2
  device_id: 15
  samplerate:
  subtype:
transcription:
  output_dir: transcripts
  model: nova-3-general
  timeout: 300
  keyterms: [keyterm1, keyterm2]
summary:
  output_dir: summaries
